### ISSUE TITLE
masterブランチの保護

### ISSUE THREAD

**Issue by piroor** [FlexConfirmMail/Thunderbird#11]
事故の発生を防ぐため、ブランチのプロテクト設定を行いたいです。
以下の3つは確定で入れたいと思っています。

* Branch name pattern：main, master, trunkなどデフォルトブランチを指定
* Require a pull request before merging ：ON（必ずプルリクエストを作成する）
* Lock branch：ON（ デフォルトブランチへのpushは禁止）

以下の設定は、入れるべきかどうか他の方のご意見を伺いたいです。

1. Require approvals ：1（プルリクエストのマージには1人のレビューが必須）
2. Require status checks to pass before merging：ON（マージ前にステータスが成功であることを要求）
3. Do not allow bypassing the above settings：ON（オーナー権限であってもレビュー無しのマージは禁止）

1と3には、以下のような利点と欠点があると考えています。

* 利点：「それ、判断ミスじゃない？」ということを第三者視点でチェックするフェーズが入るため、デフォルトブランチに意図しない変更が入ることを防げる
* 欠点：レビューする人がいない時の緊急対応ができなくなる

2には、以下のような利点と欠点があると考えています。

* 利点：後退バグが入ったままでのマージを防げる
* 欠点：緊急対応のスピードが遅くなる

拙速な緊急対応をするくらいだったら時間はかかっても確実な対応をするべきである、という方針で同意が得られるのあれば、1～3の設定も入れたいと思っています。
いかがでしょうか。

**Comment by ashie** [comment]
ひとまず`master`ブランチに対して

* `Require a pull request before merging`
* `Lock branch`

は設定しました。

**Comment by ashie** [comment]
2.は現状なにかチェック走るんでしたっけ？何もチェックが無いのであれば今のところは要らないのでは。

**Comment by piroor** [comment]
2は今はまだできていないのですが、eslintや単体テストのレベルでの後退バグ予防程度はできるかなと考えています。
4.0.0で後退バグが発生していたため、単体テストを作る事で、少なくとも同じ後退バグは以後発生を予防できるのではないかと見込んでいます。

**Comment by ashie** [comment]
> 3. Do not allow bypassing the above settings

これは設定するで良いと思います。

**Comment by ashie** [comment]
> 2は今はまだできていないのですが、eslintや単体テストのレベルでの後退バグ予防程度はできるかなと考えています。 4.0.0で後退バグが発生していたため、単体テストを作る事で、少なくとも同じ後退バグは以後発生を予防できるのではないかと見込んでいます。

では何か仕込まれたら改めて設定しましょう

**Comment by ashie** [comment]
> > 3. Do not allow bypassing the above settings
> 
> これは設定するで良いと思います。

設定しました

**Comment by ashie** [comment]
> * Lock branch：ON（ デフォルトブランチへのpushは禁止）

プルリクもマージできなくなるようなので、これは外します。

**Comment by piroor** [comment]
設定の効果を誤解していました、失礼しました。
