### ISSUE TITLE
"参照" button will not work in FlexConfirmMail 4.1.5

### ISSUE THREAD

**Issue by kenhys** [FlexConfirmMail/Thunderbird#26]
### Describe the bug

"参照" button will not work in FlexConfirmMail 4.1.5, we cant choose file.

### To Reproduce

1. Open FlexConfirmMail configuration dialog (moz-extension:/xxxxx/options/options.html
2. Click "参照" to specify "ファイル形式のリストを使用"
3. It just rest input field, but notthing happens. we can not open file chooser.

### Expected behavior

In step3, we can choose file via file chooser.

### Your Environment

```markdown
- Thunderbird version: 1:102.8.0-1 (Debian sid)
- FlexConfirmMail addon version: 4.1.5
```

### Your Configuration

```json
No need to configure because just clicking "参照" is enough to reproduce.
```

### Additional context

Here is the screen shot of debugger when clicking "参照" button.

![image](https://user-images.githubusercontent.com/225841/222665610-eb9048b3-42e1-46d8-8b86-2d2a2d0284ce.png)
screenshot

**Comment by piroor** [comment]
It depends on the native messaging host. Did you install it?

**Comment by kenhys** [comment]
Oops, not installed.

**Comment by kenhys** [comment]
Need to build manually...

**Comment by kenhys** [comment]
Workaround on Linux: Do not try to path of file, edit list in manually.

**Comment by kenhys** [comment]
Thanks, I didn't know the above background well.

**Comment by piroor** [comment]
> Workaround on Linux: Do not try to path of file, edit list in manually.

The contents of the specified file is also fetched by the native messaging host. So we anyway need to build it for Linux environments...

**Comment by kenhys** [comment]
It should be closed because of inappropriate my configuration.
