### ISSUE TITLE
Thunderbirdの会議招集(予定作成)のメールがチェックされない

### ISSUE THREAD

**Issue by tds-tamaki** [FlexConfirmMail/Thunderbird#53]
### Describe the bug

Thunderbirdで会議招集するメールが宛先チェックされずに送信されてしまう。

### To Reproduce

Thunderbirdのカレンダー画面にて「新しい予定」を選択、「参加者を追加」で宛先を追加した上で「送信して閉じる」ボタンを押下。

### Expected behavior

上記は仕様かもしれませんが、実際に社内の会議招集メールを誤って社外に送信してしまったため、可能であれば対策をお願いしたい。

### Your Environment

```markdown
- Thunderbird version:115.13.0
- FlexConfirmMail addon version:Release: 4.1.7.1
```

### Your Configuration

```json
「組織内としてメールアドレスのドメイン名」で社内ドメインを追加した以外は全てデフォルト
```

**Comment by piroor** [comment]
残念ながら、会議招集メールへの対応は現時点では不可能と考えています。

現在のFlexConfirmMailはWebExensions APIに基づいていて、メールの送信前チェックは、メールの作成画面で「送信」ボタンを押して送信が実行される時点のイベントをきっかけにして実施しています。
https://webextension-api.thunderbird.net/en/stable/compose.html#onbeforesend
そのため、現状では、メールの作成画面を経由しないメール送信操作に対してはチェックを行えないという制限があります。
カレンダーでの予定作成時にイベントが発生するようになっていれば、そこで何らかの対応を取れる可能性はありますが、残念ながら、現行のThunderbird（128）はカレンダー関係についてWebExensions APIを提供していません。

技術的には、Experimentsという機能を使用することで、WebExtensions APIが提供されていない部分へも割り込みをかけることはできますが、Experimentsを使用するとThunderbirdの特定のバージョンへの依存が強くなり、Thunderbirdの新バージョンへの追従コストが跳ね上がる恐れがあります。
現在のFlexConfirmMailは、WebExensions API（およびNative Messaging Host）の範囲でできることのみに絞って機能を提供することによってThunderbirdのバージョンアップへの追従コストを最小化する方針をとっているため、この方法は採用できないと考えています。

ただ、言い換えますと、上記のコストをご負担頂けるのであれば、Experimentsを使用してカレンダー機能に対応させられる可能性はあるとも言えます。
プロジェクトオーナーである株式会社クリアコードではThunderbirdの法人向け有償サポートを行っており、ご契約いただいているお客様からのご要望に基づくThunderbirdアドオンへの機能追加も実際に行っております。
（実際に、派生元アドオンになくFlexConfirmMailにある機能のほとんどは、そのような経緯で実装されています。）
もし本件の重要度が非常に高いようでしたら、有償サポートを通じてご依頼いただくこともご検討いただけましたら幸いです。
https://www.clear-code.com/contact/

**Comment by tds-tamaki** [comment]
ご回答ありがとうございます。内容について承知しました。

**Comment by tds-tamaki** [comment]
ご回答ありがとうございます。内容について承知しました。
